version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: doc-keeper
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "1234:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
       - ./init:/docker-entrypoint-initdb.d
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    networks:
      - minio-network
    restart: always
    command: server /data --console-address ":9001"

networks:
  minio-network:
    driver: bridge

volumes:
  postgres_data: