version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: doc-keeper
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "1234:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
       - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: