version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: doc-keeper
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "1234:5432"
    networks:
      - dockeeper-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    networks:
      - dockeeper-network
    restart: always
    command: server /data --console-address ":9001"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockeeper
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - dockeeper-network
    restart: always

networks:
  dockeeper-network:
    driver: bridge

volumes:
  postgres_data:
